export const CHARACTER_STATES = {
  IDLE_STATE: "IDLE_STATE",
  MOVE_STATE: "MOVE_STATE",
  CLIMB_STATE: "CLIMB_STATE",
  FALL_STATE: "FALL_STATE",
  DEATH_STATE: "DEATH_STATE",
  ENTRANCE_STATE: "ENTRANCE_STATE",
  TRANSITION_STATE: "TRANSITION_STATE",
  ATTACK_STATE: "ATTACK_STATE",
  HURT_STATE: "HURT_STATE",
} as const;

export const ENEMY_STATES = {
  IDLE_STATE: "ENEMY_IDLE_STATE",
  ATTACK_STATE: "ENEMY_ATTACK_STATE",
  DEATH_STATE: "ENEMY_DEATH_STATE",
  HURT_STATE: "ENEMY_HURT_STATE",
  FALL_STATE: "ENEMY_FALL_STATE",
} as const;
